# Generated by Django 2.0.4 on 2018-04-27 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BranchDetail',
            fields=[
                ('ifsc', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('bank_id', models.PositiveSmallIntegerField()),
                ('branch', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=150)),
            ],
        ),
    ]
